name: Build Modernized LeiaSR Examples with DisplayManager

on:
  push:
    branches: [ main ]
    paths:
      - 'modernized_examples/**'
      - '.github/workflows/build-modernized-examples.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'modernized_examples/**'
      - '.github/workflows/build-modernized-examples.yml'
  workflow_dispatch:

env:
  SDK_VERSION: '1.34.8-RC1'

jobs:
  build-modernized-examples:
    name: Build Modernized Examples
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        example:
          - cpp_modern
          - opengl_weaving_modern

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.21.x'

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Set SDK root environment variable
      shell: pwsh
      run: |
        $sdkPath = Resolve-Path "LeiaSR-SDK-${{ env.SDK_VERSION }}-win64"
        echo "LEIASR_SDKROOT=$sdkPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "SDK path set to: $sdkPath"

    - name: Verify SDK and modernized examples structure
      shell: pwsh
      run: |
        Write-Host "Checking SDK structure..."
        Test-Path "$env:LEIASR_SDKROOT" -PathType Container
        Test-Path "$env:LEIASR_SDKROOT/include" -PathType Container
        Test-Path "$env:LEIASR_SDKROOT/lib" -PathType Container

        Write-Host "Checking modernized examples..."
        Test-Path "modernized_examples/${{ matrix.example }}" -PathType Container
        Test-Path "modernized_examples/common/display_helper.h" -PathType Leaf

        Write-Host "Structure verified"

    - name: Configure CMake for ${{ matrix.example }}
      shell: pwsh
      run: |
        $examplePath = "modernized_examples/${{ matrix.example }}"
        $buildPath = "${{ github.workspace }}/build_modern/${{ matrix.example }}"

        Write-Host "Configuring ${{ matrix.example }}..."
        Write-Host "Example path: $examplePath"
        Write-Host "Build path: $buildPath"

        cmake -S "$examplePath" -B "$buildPath" `
          -DCMAKE_PREFIX_PATH="$env:LEIASR_SDKROOT/lib/cmake" `
          -DLEIASR_SDKROOT="$env:LEIASR_SDKROOT" `
          -DCMAKE_BUILD_TYPE=Release

    - name: Build ${{ matrix.example }}
      shell: pwsh
      run: |
        $buildPath = "${{ github.workspace }}/build_modern/${{ matrix.example }}"

        Write-Host "Building ${{ matrix.example }}..."
        cmake --build "$buildPath" --config Release --verbose

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: modernized-${{ matrix.example }}-build
        path: |
          build_modern/${{ matrix.example }}/Release/*.exe
          build_modern/${{ matrix.example }}/*.exe
        retention-days: 7
        if-no-files-found: warn

  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-modernized-examples]
    if: always()

    steps:
    - name: Check build results
      run: |
        echo "## Modernized LeiaSR Examples Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "These examples demonstrate the new IDisplayManager interface with automatic fallback to legacy Display API." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Features:**" >> $GITHUB_STEP_SUMMARY
        echo "- Modern IDisplayManager with lazy binding" >> $GITHUB_STEP_SUMMARY
        echo "- Automatic fallback to legacy Display API for older runtimes" >> $GITHUB_STEP_SUMMARY
        echo "- isValid() checks for graceful degradation" >> $GITHUB_STEP_SUMMARY
        echo "- Unified DisplayAccess helper class" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Build Status: ${{ needs.build-modernized-examples.result }}" >> $GITHUB_STEP_SUMMARY
