name: Test Migration Tool Executable

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    paths:
      - 'MIGRATION-TOOL/python-source/**'
      - '.github/workflows/test-migration-tool.yml'

jobs:
  test-executable:
    name: Test Migration Tool on Sample Example
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build executable with PyInstaller
        shell: cmd
        run: |
          cd MIGRATION-TOOL\python-source
          pip install -r requirements.txt
          pyinstaller leiasr-migrate.spec

      - name: Create test environment
        shell: cmd
        run: |
          echo Creating test directory...
          mkdir test-migration-run
          xcopy /E /I /Y LeiaSR-SDK-1.34.8-RC1-win64\examples\opengl_weaving test-migration-run\opengl_weaving

      - name: Test - Show help
        shell: cmd
        run: |
          cd MIGRATION-TOOL\python-source\dist
          echo.
          echo ========================================
          echo Testing: leiasr-migrate.exe --help
          echo ========================================
          leiasr-migrate.exe --help

      - name: Test - Analyze example
        shell: cmd
        run: |
          cd MIGRATION-TOOL\python-source\dist
          echo.
          echo ========================================
          echo Testing: Analyze opengl_weaving
          echo ========================================
          leiasr-migrate.exe analyze ..\..\..\test-migration-run --report=analysis.txt
          echo.
          echo Analysis Report:
          type analysis.txt

      - name: Test - Dry run migration
        shell: cmd
        run: |
          cd MIGRATION-TOOL\python-source\dist
          echo.
          echo ========================================
          echo Testing: Dry-run migration
          echo ========================================
          leiasr-migrate.exe migrate ..\..\..\test-migration-run --dry-run

      - name: Test - Modern migration (default)
        shell: cmd
        run: |
          cd MIGRATION-TOOL\python-source\dist
          echo.
          echo ========================================
          echo Testing: Modern migration (default)
          echo ========================================
          leiasr-migrate.exe migrate ..\..\..\test-migration-run --yes

      - name: Verify modern migration results
        shell: cmd
        run: |
          echo.
          echo ========================================
          echo Verifying modern migration results
          echo ========================================
          echo.
          echo Checking for .legacy files:
          dir /B /S test-migration-run\*.legacy
          echo.
          echo Checking migrated main.cpp has IDisplayManager:
          findstr /C:"IDisplayManager" test-migration-run\opengl_weaving\opengl_weaving\main.cpp || exit /b 1
          echo.
          echo Checking migrated main.cpp has getPrimaryActiveSRDisplay:
          findstr /C:"getPrimaryActiveSRDisplay" test-migration-run\opengl_weaving\opengl_weaving\main.cpp || exit /b 1
          echo.
          echo Checking migrated main.cpp does NOT have display_helper.h:
          findstr /C:"display_helper.h" test-migration-run\opengl_weaving\opengl_weaving\main.cpp && exit /b 1 || echo OK - no helper include found
          echo.
          echo Checking migrated main.cpp does NOT have DisplayAccess:
          findstr /C:"DisplayAccess" test-migration-run\opengl_weaving\opengl_weaving\main.cpp && exit /b 1 || echo OK - no DisplayAccess found
          echo.
          echo Modern migration verification PASSED!

      - name: Create second test environment for legacy mode
        shell: cmd
        run: |
          echo.
          echo Creating second test directory for legacy fallback mode...
          mkdir test-migration-legacy
          xcopy /E /I /Y LeiaSR-SDK-1.34.8-RC1-win64\examples\opengl_weaving test-migration-legacy\opengl_weaving

      - name: Test - Legacy fallback migration
        shell: cmd
        run: |
          cd MIGRATION-TOOL\python-source\dist
          echo.
          echo ========================================
          echo Testing: Legacy fallback migration
          echo ========================================
          leiasr-migrate.exe migrate ..\..\..\test-migration-legacy --legacy-fallback --yes

      - name: Verify legacy fallback migration results
        shell: cmd
        run: |
          echo.
          echo ========================================
          echo Verifying legacy fallback migration
          echo ========================================
          echo.
          echo Checking for .legacy files:
          dir /B /S test-migration-legacy\*.legacy
          echo.
          echo Checking migrated main.cpp has SRDISPLAY_LAZYBINDING:
          findstr /C:"SRDISPLAY_LAZYBINDING" test-migration-legacy\opengl_weaving\opengl_weaving\main.cpp || exit /b 1
          echo.
          echo Checking migrated main.cpp has display_helper.h:
          findstr /C:"display_helper.h" test-migration-legacy\opengl_weaving\opengl_weaving\main.cpp || exit /b 1
          echo.
          echo Checking migrated main.cpp has DisplayAccess:
          findstr /C:"DisplayAccess" test-migration-legacy\opengl_weaving\opengl_weaving\main.cpp || exit /b 1
          echo.
          echo Checking display_helper.h was created:
          dir test-migration-legacy\opengl_weaving\display_helper.h || exit /b 1
          echo.
          echo Legacy fallback migration verification PASSED!

      - name: Show file comparison
        shell: cmd
        continue-on-error: true
        run: |
          echo.
          echo ========================================
          echo Showing first differences between files
          echo ========================================
          fc /N /L /C test-migration-run\opengl_weaving\opengl_weaving\main.cpp.legacy test-migration-run\opengl_weaving\opengl_weaving\main.cpp | more +10

      - name: Upload migration results
        uses: actions/upload-artifact@v4
        with:
          name: migration-test-results
          path: |
            MIGRATION-TOOL/python-source/dist/analysis.txt
            test-migration-run/opengl_weaving/opengl_weaving/main.cpp
            test-migration-run/opengl_weaving/opengl_weaving/main.cpp.legacy
            test-migration-legacy/opengl_weaving/opengl_weaving/main.cpp
            test-migration-legacy/opengl_weaving/opengl_weaving/main.cpp.legacy
            test-migration-legacy/opengl_weaving/display_helper.h
          retention-days: 7

      - name: Test summary
        shell: cmd
        run: |
          echo.
          echo ========================================
          echo TEST SUMMARY v1.2.0
          echo ========================================
          echo [PASS] Executable runs without errors
          echo [PASS] Help command works
          echo [PASS] Analyze detects patterns
          echo [PASS] Dry-run previews changes
          echo.
          echo MODERN MODE (DEFAULT):
          echo [PASS] Migration creates .legacy files
          echo [PASS] Migration uses IDisplayManager
          echo [PASS] Migration calls getPrimaryActiveSRDisplay
          echo [PASS] No display_helper.h created
          echo [PASS] No DisplayAccess usage
          echo.
          echo LEGACY FALLBACK MODE:
          echo [PASS] Migration creates .legacy files
          echo [PASS] Migration adds SRDISPLAY_LAZYBINDING
          echo [PASS] Migration includes display_helper.h
          echo [PASS] Migration converts to DisplayAccess
          echo [PASS] display_helper.h file created
          echo.
          echo All tests PASSED!
