name: Test SDK Example Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-sdk-example:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Display MSBuild version
      run: msbuild -version

    - name: Copy SDK example to build location
      run: |
        # Copy the entire directx11_weaving example to a build directory
        xcopy /E /I /Y "simulatedreality-SDK-1.34.8.31132-win64-Release\examples\directx11_weaving" "build_test\directx11_weaving"
      shell: cmd

    - name: List example files
      run: |
        echo "Listing files in the example directory:"
        dir /S "build_test\directx11_weaving"
      shell: cmd

    - name: Setup CMake
      run: |
        echo "CMake version:"
        cmake --version
      shell: cmd

    - name: Configure CMake
      run: |
        cd build_test\directx11_weaving
        cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="%CD%\..\..\simulatedreality-SDK-1.34.8.31132-win64-Release"
      shell: cmd

    - name: Build with CMake
      run: |
        cd build_test\directx11_weaving
        cmake --build build --config Release
      shell: cmd

    - name: List build output
      run: |
        echo "Build output directory:"
        dir /S "build_test\directx11_weaving\build\Release"
      shell: cmd
      continue-on-error: true

    - name: Upload SDK example build
      uses: actions/upload-artifact@v4
      with:
        name: directx11_weaving_example
        path: build_test/directx11_weaving/build/Release/*.exe
        if-no-files-found: warn
